name: Update Yield Curve

on:
  schedule:
    - cron: '0 1 * * *' # 01:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: update-yield-curve
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib

      - name: Generate chart
        env:
          MPLBACKEND: Agg
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python "Yield Curve Comparison.py"

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A yield_curve_us_canada.png
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto-update yield curve image [skip ci]"
          git push

